name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    needs: setup-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Run lint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: setup-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Run type check
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    needs: setup-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Run tests
        run: npm test
